version: '3.9'

services:
  app:
    build: .
    container_name: nycbike_app
    network_mode: host
    restart: always
    env_file:
      - .env
    depends_on:
      - valkey

  valkey:
    image: valkey/valkey:latest
    container_name: website_valkey
    network_mode: host
    restart: always
    volumes:
      - valkey_data:/data
    command: ['valkey-server', '--appendonly', 'yes']

volumes:
  valkey_data:
