name: Deploy Dev to Server

on:
  push:
    branches:
      - dev # Only deploy when dev branch changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/deploy/website/newyork-citybike || exit 1
            git fetch origin dev
            git checkout dev
            git pull origin dev
            # If you need to build:
            # npm install && npm run build
            # Or restart service:
            # systemctl restart my-app
          EOF
